stages:
  clean_data:
    cmd: python src/clean_data.py  --config=params.yaml
    deps:
    - src/get_data.py
    - src/clean_data.py
    - data_given/chennai_housing_price.csv
    outs:
    - data/cleaned/chennai_housing_price.csv
  
  split_data:
    cmd: python src/split_data.py  --config=params.yaml
    deps:
    - src/split_data.py
    - data/cleaned/chennai_housing_price.csv
    outs:
    - data/processed/train_chennaihousingprice.csv
    - data/processed/test_chennaihousingprice.csv
  
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py  --config=params.yaml
    deps:
    - src/train_and_evaluate.py
    - data/processed/train_chennaihousingprice.csv
    - data/processed/test_chennaihousingprice.csv
    params:
    - estimators.RandomForest.params.max_depth
    - estimators.RandomForest.params.max_features
    - estimators.RandomForest.params.n_estimators
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_model/pipeline.joblib
