stages:
  clean_data:
    cmd: python src/clean_data.py  --config=params.yaml
    deps:
    - src/get_data.py
    - src/clean_data.py
    - data_given/chennai_housing_price.csv
    outs:
    - data/cleaned/chennai_housing_price.csv
  split_data:
    cmd: python src/split_data.py  --config=params.yaml
    deps:
    - src/split_data.py
    - data/cleaned/chennai_housing_price.csv
    outs:
    - data/processed/train_chennaihousingprice.csv
    - data/processed/test_chennaihousingprice.csv